[tool.black]
line-length = 88
target-version = ['py312']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | static
  | settings
  | venv
  | manage.py
)/
'''

[tool.isort]
profile = "black"
line_length = 88
