# Generated by Django 5.1.1 on 2024-09-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
