# Generated by Django 5.1.1 on 2024-09-21 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_metrics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(choices=[('BP', 'Blood Pressure'), ('Sugar', 'Sugar Level'), ('Hemoglobin', 'Hemoglobin')])),
                ('componentValue', models.FloatField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('measuredDateTime', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
