# Generated by Django 5.1.1 on 2024-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_bmi_remove_patient_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaldata',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clinicaldata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
